# Generated by Django 4.1.5 on 2023-03-17 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_token', models.CharField(default=0, max_length=200)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('pro_pic', models.ImageField(default='default_pic.jpg', upload_to='ProfilePic')),
                ('Cov_pic', models.ImageField(default='default_cover.jpg', upload_to='ProfilePic')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='multi_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(blank=True, max_length=50, null=True)),
                ('Sub_division', models.CharField(blank=True, max_length=50, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivery_Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
