# Generated by Django 4.1.5 on 2023-03-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='purchesed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Confirm', models.BooleanField(default=False)),
                ('Confirm_Time', models.DateTimeField(auto_now_add=True)),
                ('Payment_ID', models.CharField(blank=True, max_length=300, null=True)),
                ('Order_ID', models.CharField(blank=True, max_length=300, null=True)),
                ('Status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], max_length=30)),
                ('Delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.multi_address')),
                ('Order_Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Products.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
