# Generated by Django 4.1.5 on 2023-03-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_cart_purchesed_cart_updated_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quentity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
