# Generated by Django 4.1.5 on 2023-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_order_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Pyment_Method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Pyple', 'Pyple'), ('SSL Commerz', 'SSL Commerz')], default='Cash On Delivery', max_length=50),
        ),
    ]
